#!/bin/bash

# hack because devserver doesn't like running too many tests for me :-(
#
# see https://code.google.com/p/googleappengine/issues/detail?id=10824

awk '/func.*Test[a-zA-Z]*\(.*{/ { print $4}' mapreduce_test.go  | sed 's/(.*//' | while read test; do
	echo -n "$test "
	goapp test ./... -check.f "^${test}$" $*

done
